compiler:
- gcc
- clang
language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist
  user: huntzhan
  password:
    secure: cWEel4EE2yyXl1G9DgHRugki/1gowXMmLHbLrZ6UzOlcnIfdawqr1oclCTAlOJMPSzVPwKwZyNTlB5yvlm/j6Wa2GrBNqKi1UNsZsW0Vod3PpEd9LmB5e69Yfy8cTYjAf8HQLXPZv1qUBvceqy07TFzhf27JQjbyTQDJoAKiW9b5Z5oeN3EDUuuQxvrbIfnRXfC5OyBX9h0ObU4Y87gpxrQTAt2f2h5SWzDEKKrJXYGtv9JZP21yFQVnf036EsU6AJBSXoQvato0L7E50BheXWHzjUqw1+MdjxDUXxSFjbpLicnLwtgwjFNoW8wUMZpsi22jj5CiTq+WdiYUO8fSPSOk5yCq+1uqabL5O90Hme/b55qoqTzvBWEax4wxi+ib7xrOADgpF936E0x82/Wf8xyyo8qiAd2mRtSXyTG6YzIup5GSMUKBP8WMPpfjQa+eVokpTLlkkHwg4hqpkCS2NFM6M/Gm4TqgMN03igUPvQX4GqP++eNuAQ5SMK81hqUZifuRjMRaxWtUtYRhQnN4p8pbbcNKPNYm5dslFhB9nWUa1/3Fn/sfCJa69CJtZszuEzMV8X6B6dUCztv9YUxEYCPXypWefoaqqM2y9Jx8jQeSEZawAEYiR5lrgdsfzWINsXZyd/VDlTvaZGzt0bTDIrJyxeaC9dnriHC4L6W+LPg=
  on:
    tags: true
    repo: cnt-dev/cnt.sam
    python: 3.6
